### ISSUE TITLE
Compare fails (loop?)

### ISSUE THREAD

**Issue by Discostu36** [zedlabs/ElementHistoryDialog#8]
[Vespucci](https://github.com/MarcusWolschon/osmeditor4android) uses ElementHistoryDialog. When comparing version 5 with version 6 of https://www.openstreetmap.org/way/1098448370, the app crashes. @simonpoole thinks a loop might be happening at this specific compare. 

See https://github.com/MarcusWolschon/osmeditor4android/issues/2187

**Comment by simonpoole** [comment]
It seems to be an infinite loop in addWayTableRows. If I have a sec I'll give it a look. The way nodes are inverted in this case, so there should 4 changes or so.
